development:
  adapter: mysql2
  database: my_development
  username: root
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: my_test
  username: root
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: my
  username: root
  host: localhost
  pool: 5
  timeout: 5000
